CREATE TABLE Employee (
    EMP_ID NVARCHAR(12) PRIMARY KEY,
    NAME NVARCHAR(64),
    EMAIL NVARCHAR(128),
    FLOOR_SEAT_SEQ NVARCHAR(64)
);

CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ NVARCHAR(64) PRIMARY KEY,
    FLOOR_NO NVARCHAR(32),
    SEAT_NO NVARCHAR(32)
);

CREATE PROCEDURE UpdateEmpSeat (@EMP_ID NVARCHAR(12), @FLOOR_NO NVARCHAR(32), @SEAT_NO NVARCHAR(32))
AS
BEGIN
    UPDATE Employee SET FLOOR_SEAT_SEQ = @FLOOR_NO+@SEAT_NO WHERE EMP_ID = @EMP_ID;
END;